name: Basic CI for TypeScript Project

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb5afa53bb794d44cc353d # Pin to specific SHA

    - name: Setup Node.js
      uses: actions/setup-node@v4 # Pin to specific version
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Cache dependencies
      uses: actions/cache@v4 # Pin to specific version
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      run: npm install

    - name: Run Lint
      run: npm run lint

    - name: Run Tests
      run: npm test

    - name: Run Security Audit
      run: npm audit || true

    - name: Build TypeScript Project
      run: npm run build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4 # Pin to specific version
      with:
        name: build-artifacts
        path: dist/
        retention-days: 7
