name: CD Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    if: github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: ./dist
    - name: Deploy to production
      env:
        KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
        # ... other deployment secrets
      run: |
        echo "$KUBECONFIG_DATA" | base64 --decode > kubeconfig.yaml
        export KUBECONFIG=$(pwd)/kubeconfig.yaml
        kubectl apply -f ./dist/k8s-manifests/
        echo "Deployment to production initiated."