version: '3.8'

services:
  app:
    build:
      context: ./typescript-node-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./typescript-node-app/src:/app/src # Mount source for hot-reloading
      - /app/node_modules # Keep node_modules inside container
    environment:
      NODE_ENV: development
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  db_data:
