stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build_job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  artifacts:
    paths:
      - build/
  only:
    - main

test_job:
  stage: test
  image: node:latest
  script:
    - npm install
    - npm test
  only:
    - main

deploy_job:
  stage: deploy
  image: alpine/helm:latest
  script:
    - echo "Deploying $DOCKER_IMAGE to Kubernetes..."
    - helm upgrade --install my-app ./helm-chart --set image.repository=$CI_REGISTRY_IMAGE --set image.tag=$CI_COMMIT_SHORT_SHA
  environment: production
  only:
    - main